function out = Model_g(in1,in2,in3,in4)
%MODEL_G
%    OUT = MODEL_G(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    09-Nov-2021 15:26:37

%None
K_Q__Propeller = in4(6,:);
K_T__Propeller = in4(7,:);
N_p__Battery = in4(8,:);
N_s__Battery = in4(9,:);
R_s__Battery = in4(12,:);
Rm__Motor = in4(13,:);
kV__Motor = in4(14,:);
u1 = in2(1,:);
u2 = in2(2,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
et1 = (sqrt(6.0).*(N_p__Battery.*x3.*9.0e+2+N_p__Battery.*Rm__Motor.*x3.*6.0e+3+N_p__Battery.*u1.^2.*x3.*2.7e+1-N_p__Battery.*u1.*u2.*x2.*2.7e+1+N_s__Battery.*R_s__Battery.*u1.^2.*x3.*9.0e+3-N_p__Battery.*N_s__Battery.*kV__Motor.*u2.*pi.*1.11e+2-N_s__Battery.*R_s__Battery.*u1.*u2.*x2.*9.0e+3-N_p__Battery.*N_s__Battery.*Rm__Motor.*kV__Motor.*u2.*pi.*7.4e+2))./(kV__Motor.*pi.*(N_p__Battery.*9.0e+2+N_p__Battery.*Rm__Motor.*1.2e+4+N_p__Battery.*Rm__Motor.^2.*4.0e+4+N_p__Battery.*u1.^2.*2.7e+1+N_p__Battery.*u2.^2.*2.7e+1+N_s__Battery.*R_s__Battery.*u1.^2.*9.0e+3+N_s__Battery.*R_s__Battery.*u2.^2.*9.0e+3+N_p__Battery.*Rm__Motor.*u1.^2.*1.8e+2+N_p__Battery.*Rm__Motor.*u2.^2.*1.8e+2+N_s__Battery.*R_s__Battery.*Rm__Motor.*u1.^2.*6.0e+4+N_s__Battery.*R_s__Battery.*Rm__Motor.*u2.^2.*6.0e+4));
et2 = -1.0e+2;
et3 = (sqrt(6.0).*(N_p__Battery.*x2.*9.0e+2+N_p__Battery.*Rm__Motor.*x2.*6.0e+3+N_p__Battery.*u2.^2.*x2.*2.7e+1-N_p__Battery.*u1.*u2.*x3.*2.7e+1+N_s__Battery.*R_s__Battery.*u2.^2.*x2.*9.0e+3-N_p__Battery.*N_s__Battery.*kV__Motor.*u1.*pi.*1.11e+2-N_s__Battery.*R_s__Battery.*u1.*u2.*x3.*9.0e+3-N_p__Battery.*N_s__Battery.*Rm__Motor.*kV__Motor.*u1.*pi.*7.4e+2))./(kV__Motor.*pi.*(N_p__Battery.*9.0e+2+N_p__Battery.*Rm__Motor.*1.2e+4+N_p__Battery.*Rm__Motor.^2.*4.0e+4+N_p__Battery.*u1.^2.*2.7e+1+N_p__Battery.*u2.^2.*2.7e+1+N_s__Battery.*R_s__Battery.*u1.^2.*9.0e+3+N_s__Battery.*R_s__Battery.*u2.^2.*9.0e+3+N_p__Battery.*Rm__Motor.*u1.^2.*1.8e+2+N_p__Battery.*Rm__Motor.*u2.^2.*1.8e+2+N_s__Battery.*R_s__Battery.*Rm__Motor.*u1.^2.*6.0e+4+N_s__Battery.*R_s__Battery.*Rm__Motor.*u2.^2.*6.0e+4));
et4 = -1.0e+2;
et5 = sqrt(6.0)./(kV__Motor.*pi.*(N_p__Battery.*9.0e+2+N_p__Battery.*Rm__Motor.*1.2e+4+N_p__Battery.*Rm__Motor.^2.*4.0e+4+N_p__Battery.*u1.^2.*2.7e+1+N_p__Battery.*u2.^2.*2.7e+1+N_s__Battery.*R_s__Battery.*u1.^2.*9.0e+3+N_s__Battery.*R_s__Battery.*u2.^2.*9.0e+3+N_p__Battery.*Rm__Motor.*u1.^2.*1.8e+2+N_p__Battery.*Rm__Motor.*u2.^2.*1.8e+2+N_s__Battery.*R_s__Battery.*Rm__Motor.*u1.^2.*6.0e+4+N_s__Battery.*R_s__Battery.*Rm__Motor.*u2.^2.*6.0e+4));
et6 = (N_p__Battery.*x3.*2.7e+3+N_p__Battery.*Rm__Motor.*x3.*1.8e+4+N_p__Battery.*u1.^2.*x3.*8.1e+1+N_p__Battery.*u2.^2.*x3.*8.1e+1+N_s__Battery.*R_s__Battery.*u1.^2.*x3.*2.7e+4+N_s__Battery.*R_s__Battery.*u2.^2.*x3.*2.7e+4+N_p__Battery.*Rm__Motor.*u2.^2.*x3.*5.4e+2+N_p__Battery.*Rm__Motor.*u1.*u2.*x2.*5.4e+2+N_s__Battery.*R_s__Battery.*Rm__Motor.*u2.^2.*x3.*1.8e+5+N_p__Battery.*N_s__Battery.*Rm__Motor.*kV__Motor.*u2.*pi.*2.22e+3+N_s__Battery.*R_s__Battery.*Rm__Motor.*u1.*u2.*x2.*1.8e+5+N_p__Battery.*N_s__Battery.*Rm__Motor.^2.*kV__Motor.*u2.*pi.*1.48e+4).*5.0;
et7 = sqrt(6.0)./(kV__Motor.*pi.*(N_p__Battery.*9.0e+2+N_p__Battery.*Rm__Motor.*1.2e+4+N_p__Battery.*Rm__Motor.^2.*4.0e+4+N_p__Battery.*u1.^2.*2.7e+1+N_p__Battery.*u2.^2.*2.7e+1+N_s__Battery.*R_s__Battery.*u1.^2.*9.0e+3+N_s__Battery.*R_s__Battery.*u2.^2.*9.0e+3+N_p__Battery.*Rm__Motor.*u1.^2.*1.8e+2+N_p__Battery.*Rm__Motor.*u2.^2.*1.8e+2+N_s__Battery.*R_s__Battery.*Rm__Motor.*u1.^2.*6.0e+4+N_s__Battery.*R_s__Battery.*Rm__Motor.*u2.^2.*6.0e+4));
et8 = (N_p__Battery.*x2.*2.7e+3+N_p__Battery.*Rm__Motor.*x2.*1.8e+4+N_p__Battery.*u1.^2.*x2.*8.1e+1+N_p__Battery.*u2.^2.*x2.*8.1e+1+N_s__Battery.*R_s__Battery.*u1.^2.*x2.*2.7e+4+N_s__Battery.*R_s__Battery.*u2.^2.*x2.*2.7e+4+N_p__Battery.*Rm__Motor.*u1.^2.*x2.*5.4e+2+N_p__Battery.*Rm__Motor.*u1.*u2.*x3.*5.4e+2+N_s__Battery.*R_s__Battery.*Rm__Motor.*u1.^2.*x2.*1.8e+5+N_p__Battery.*N_s__Battery.*Rm__Motor.*kV__Motor.*u1.*pi.*2.22e+3+N_s__Battery.*R_s__Battery.*Rm__Motor.*u1.*u2.*x3.*1.8e+5+N_p__Battery.*N_s__Battery.*Rm__Motor.^2.*kV__Motor.*u1.*pi.*1.48e+4).*5.0;
mt1 = [x1,x2,x3,((N_p__Battery.*u1.*x2.*2.7e+1+N_p__Battery.*u2.*x3.*2.7e+1+N_p__Battery.*N_s__Battery.*kV__Motor.*pi.*1.11e+2+N_s__Battery.*R_s__Battery.*u1.*x2.*9.0e+3+N_s__Battery.*R_s__Battery.*u2.*x3.*9.0e+3+N_p__Battery.*N_s__Battery.*Rm__Motor.*kV__Motor.*pi.*7.4e+2).*1.0e+1)./(kV__Motor.*pi.*(N_p__Battery.*3.0e+2+N_p__Battery.*Rm__Motor.*2.0e+3+N_p__Battery.*u1.^2.*9.0+N_p__Battery.*u2.^2.*9.0+N_s__Battery.*R_s__Battery.*u1.^2.*3.0e+3+N_s__Battery.*R_s__Battery.*u2.^2.*3.0e+3))];
mt2 = [((N_p__Battery.*u1.*x2.*3.0e+2+N_p__Battery.*u2.*x3.*3.0e+2-N_p__Battery.*N_s__Battery.*kV__Motor.*u1.^2.*pi.*3.7e+1-N_p__Battery.*N_s__Battery.*kV__Motor.*u2.^2.*pi.*3.7e+1).*-3.0e+2)./(kV__Motor.*pi.*(N_p__Battery.*3.0e+2+N_p__Battery.*Rm__Motor.*2.0e+3+N_p__Battery.*u1.^2.*9.0+N_p__Battery.*u2.^2.*9.0+N_s__Battery.*R_s__Battery.*u1.^2.*3.0e+3+N_s__Battery.*R_s__Battery.*u2.^2.*3.0e+3))];
mt3 = [((N_p__Battery.*x2.*9.0e+2+N_p__Battery.*Rm__Motor.*x2.*6.0e+3+N_p__Battery.*u2.^2.*x2.*2.7e+1-N_p__Battery.*u1.*u2.*x3.*2.7e+1+N_s__Battery.*R_s__Battery.*u2.^2.*x2.*9.0e+3-N_p__Battery.*N_s__Battery.*kV__Motor.*u1.*pi.*1.11e+2-N_s__Battery.*R_s__Battery.*u1.*u2.*x3.*9.0e+3-N_p__Battery.*N_s__Battery.*Rm__Motor.*kV__Motor.*u1.*pi.*7.4e+2).*-3.0e+2)./(kV__Motor.*pi.*(N_p__Battery.*9.0e+2+N_p__Battery.*Rm__Motor.*1.2e+4+N_p__Battery.*Rm__Motor.^2.*4.0e+4+N_p__Battery.*u1.^2.*2.7e+1+N_p__Battery.*u2.^2.*2.7e+1+N_s__Battery.*R_s__Battery.*u1.^2.*9.0e+3+N_s__Battery.*R_s__Battery.*u2.^2.*9.0e+3+N_p__Battery.*Rm__Motor.*u1.^2.*1.8e+2+N_p__Battery.*Rm__Motor.*u2.^2.*1.8e+2+N_s__Battery.*R_s__Battery.*Rm__Motor.*u1.^2.*6.0e+4+N_s__Battery.*R_s__Battery.*Rm__Motor.*u2.^2.*6.0e+4)),et7.*et8];
mt4 = [((N_p__Battery.*x3.*9.0e+2+N_p__Battery.*Rm__Motor.*x3.*6.0e+3+N_p__Battery.*u1.^2.*x3.*2.7e+1-N_p__Battery.*u1.*u2.*x2.*2.7e+1+N_s__Battery.*R_s__Battery.*u1.^2.*x3.*9.0e+3-N_p__Battery.*N_s__Battery.*kV__Motor.*u2.*pi.*1.11e+2-N_s__Battery.*R_s__Battery.*u1.*u2.*x2.*9.0e+3-N_p__Battery.*N_s__Battery.*Rm__Motor.*kV__Motor.*u2.*pi.*7.4e+2).*-3.0e+2)./(kV__Motor.*pi.*(N_p__Battery.*9.0e+2+N_p__Battery.*Rm__Motor.*1.2e+4+N_p__Battery.*Rm__Motor.^2.*4.0e+4+N_p__Battery.*u1.^2.*2.7e+1+N_p__Battery.*u2.^2.*2.7e+1+N_s__Battery.*R_s__Battery.*u1.^2.*9.0e+3+N_s__Battery.*R_s__Battery.*u2.^2.*9.0e+3+N_p__Battery.*Rm__Motor.*u1.^2.*1.8e+2+N_p__Battery.*Rm__Motor.*u2.^2.*1.8e+2+N_s__Battery.*R_s__Battery.*Rm__Motor.*u1.^2.*6.0e+4+N_s__Battery.*R_s__Battery.*Rm__Motor.*u2.^2.*6.0e+4)),et5.*et6];
mt5 = [et3.*et4,et1.*et2,K_T__Propeller.*x2.^2,K_Q__Propeller.*x2.^2,K_T__Propeller.*x3.^2,K_Q__Propeller.*x3.^2];
out = reshape([mt1,mt2,mt3,mt4,mt5],15,1);
