function [out1,out2] = SymListTest(x1,x2)
%SYMLISTTEST
%    [OUT1,OUT2] = SYMLISTTEST(X1,X2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    10-Nov-2021 15:51:19

out1 = x1+x2;
if nargout > 1
    out2 = x1.*x2;
end
