function out = Model_f(in1,in2,in3,in4)
%MODEL_F
%    OUT = MODEL_F(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    09-Nov-2021 15:26:37

%None
J_r__MotorProp = in4(5,:);
K_Q__Propeller = in4(6,:);
N_p__Battery = in4(8,:);
N_s__Battery = in4(9,:);
Q__Battery = in4(11,:);
R_s__Battery = in4(12,:);
Rm__Motor = in4(13,:);
kV__Motor = in4(14,:);
u1 = in2(1,:);
u2 = in2(2,:);
x2 = in1(2,:);
x3 = in1(3,:);
et1 = sqrt(2.0).*sqrt(3.0).*sqrt(6.0).*N_p__Battery.*x3.*1.35e+6+K_Q__Propeller.*N_p__Battery.*kV__Motor.^2.*x3.^2.*pi.^2.*9.0e+2+sqrt(2.0).*sqrt(3.0).*sqrt(6.0).*N_p__Battery.*u1.^2.*x3.*4.05e+4+K_Q__Propeller.*N_p__Battery.*kV__Motor.^2.*u1.^2.*x3.^2.*pi.^2.*2.7e+1+K_Q__Propeller.*N_p__Battery.*kV__Motor.^2.*u2.^2.*x3.^2.*pi.^2.*2.7e+1+sqrt(2.0).*sqrt(3.0).*sqrt(6.0).*N_p__Battery.*Rm__Motor.*x3.*9.0e+6+K_Q__Propeller.*N_p__Battery.*Rm__Motor.*kV__Motor.^2.*x3.^2.*pi.^2.*1.2e+4+K_Q__Propeller.*N_p__Battery.*Rm__Motor.^2.*kV__Motor.^2.*x3.^2.*pi.^2.*4.0e+4-sqrt(2.0).*sqrt(3.0).*sqrt(6.0).*N_p__Battery.*u1.*u2.*x2.*4.05e+4;
et2 = sqrt(2.0).*sqrt(3.0).*sqrt(6.0).*N_s__Battery.*R_s__Battery.*u1.^2.*x3.*1.35e+7+K_Q__Propeller.*N_s__Battery.*R_s__Battery.*kV__Motor.^2.*u1.^2.*x3.^2.*pi.^2.*9.0e+3+K_Q__Propeller.*N_s__Battery.*R_s__Battery.*kV__Motor.^2.*u2.^2.*x3.^2.*pi.^2.*9.0e+3+K_Q__Propeller.*N_p__Battery.*Rm__Motor.*kV__Motor.^2.*u1.^2.*x3.^2.*pi.^2.*1.8e+2+K_Q__Propeller.*N_p__Battery.*Rm__Motor.*kV__Motor.^2.*u2.^2.*x3.^2.*pi.^2.*1.8e+2-sqrt(2.0).*sqrt(3.0).*sqrt(6.0).*N_p__Battery.*N_s__Battery.*kV__Motor.*u2.*pi.*1.665e+5-sqrt(2.0).*sqrt(3.0).*sqrt(6.0).*N_s__Battery.*R_s__Battery.*u1.*u2.*x2.*1.35e+7+K_Q__Propeller.*N_s__Battery.*R_s__Battery.*Rm__Motor.*kV__Motor.^2.*u1.^2.*x3.^2.*pi.^2.*6.0e+4;
et3 = K_Q__Propeller.*N_s__Battery.*R_s__Battery.*Rm__Motor.*kV__Motor.^2.*u2.^2.*x3.^2.*pi.^2.*6.0e+4-sqrt(2.0).*sqrt(3.0).*sqrt(6.0).*N_p__Battery.*N_s__Battery.*Rm__Motor.*kV__Motor.*u2.*pi.*1.11e+6;
et4 = sqrt(2.0).*sqrt(3.0).*sqrt(6.0).*N_p__Battery.*x2.*1.35e+6+K_Q__Propeller.*N_p__Battery.*kV__Motor.^2.*x2.^2.*pi.^2.*9.0e+2+sqrt(2.0).*sqrt(3.0).*sqrt(6.0).*N_p__Battery.*u2.^2.*x2.*4.05e+4+K_Q__Propeller.*N_p__Battery.*kV__Motor.^2.*u1.^2.*x2.^2.*pi.^2.*2.7e+1+K_Q__Propeller.*N_p__Battery.*kV__Motor.^2.*u2.^2.*x2.^2.*pi.^2.*2.7e+1+sqrt(2.0).*sqrt(3.0).*sqrt(6.0).*N_p__Battery.*Rm__Motor.*x2.*9.0e+6+K_Q__Propeller.*N_p__Battery.*Rm__Motor.*kV__Motor.^2.*x2.^2.*pi.^2.*1.2e+4+K_Q__Propeller.*N_p__Battery.*Rm__Motor.^2.*kV__Motor.^2.*x2.^2.*pi.^2.*4.0e+4-sqrt(2.0).*sqrt(3.0).*sqrt(6.0).*N_p__Battery.*u1.*u2.*x3.*4.05e+4;
et5 = sqrt(2.0).*sqrt(3.0).*sqrt(6.0).*N_s__Battery.*R_s__Battery.*u2.^2.*x2.*1.35e+7+K_Q__Propeller.*N_s__Battery.*R_s__Battery.*kV__Motor.^2.*u1.^2.*x2.^2.*pi.^2.*9.0e+3+K_Q__Propeller.*N_s__Battery.*R_s__Battery.*kV__Motor.^2.*u2.^2.*x2.^2.*pi.^2.*9.0e+3+K_Q__Propeller.*N_p__Battery.*Rm__Motor.*kV__Motor.^2.*u1.^2.*x2.^2.*pi.^2.*1.8e+2+K_Q__Propeller.*N_p__Battery.*Rm__Motor.*kV__Motor.^2.*u2.^2.*x2.^2.*pi.^2.*1.8e+2-sqrt(2.0).*sqrt(3.0).*sqrt(6.0).*N_p__Battery.*N_s__Battery.*kV__Motor.*u1.*pi.*1.665e+5-sqrt(2.0).*sqrt(3.0).*sqrt(6.0).*N_s__Battery.*R_s__Battery.*u1.*u2.*x3.*1.35e+7+K_Q__Propeller.*N_s__Battery.*R_s__Battery.*Rm__Motor.*kV__Motor.^2.*u1.^2.*x2.^2.*pi.^2.*6.0e+4;
et6 = K_Q__Propeller.*N_s__Battery.*R_s__Battery.*Rm__Motor.*kV__Motor.^2.*u2.^2.*x2.^2.*pi.^2.*6.0e+4-sqrt(2.0).*sqrt(3.0).*sqrt(6.0).*N_p__Battery.*N_s__Battery.*Rm__Motor.*kV__Motor.*u1.*pi.*1.11e+6;
mt1 = [((u1.*x2.*3.0e+2+u2.*x3.*3.0e+2-N_s__Battery.*kV__Motor.*u1.^2.*pi.*3.7e+1-N_s__Battery.*kV__Motor.*u2.^2.*pi.*3.7e+1).*(2.5e+2./3.0))./(Q__Battery.*kV__Motor.*pi.*(N_p__Battery.*3.0e+2+N_p__Battery.*Rm__Motor.*2.0e+3+N_p__Battery.*u1.^2.*9.0+N_p__Battery.*u2.^2.*9.0+N_s__Battery.*R_s__Battery.*u1.^2.*3.0e+3+N_s__Battery.*R_s__Battery.*u2.^2.*3.0e+3))];
mt2 = [-(1.0./kV__Motor.^2.*1.0./pi.^2.*(et4+et5+et6))./(J_r__MotorProp.*(N_p__Battery.*9.0e+2+N_p__Battery.*Rm__Motor.*1.2e+4+N_p__Battery.*Rm__Motor.^2.*4.0e+4+N_p__Battery.*u1.^2.*2.7e+1+N_p__Battery.*u2.^2.*2.7e+1+N_s__Battery.*R_s__Battery.*u1.^2.*9.0e+3+N_s__Battery.*R_s__Battery.*u2.^2.*9.0e+3+N_p__Battery.*Rm__Motor.*u1.^2.*1.8e+2+N_p__Battery.*Rm__Motor.*u2.^2.*1.8e+2+N_s__Battery.*R_s__Battery.*Rm__Motor.*u1.^2.*6.0e+4+N_s__Battery.*R_s__Battery.*Rm__Motor.*u2.^2.*6.0e+4))];
mt3 = [-(1.0./kV__Motor.^2.*1.0./pi.^2.*(et1+et2+et3))./(J_r__MotorProp.*(N_p__Battery.*9.0e+2+N_p__Battery.*Rm__Motor.*1.2e+4+N_p__Battery.*Rm__Motor.^2.*4.0e+4+N_p__Battery.*u1.^2.*2.7e+1+N_p__Battery.*u2.^2.*2.7e+1+N_s__Battery.*R_s__Battery.*u1.^2.*9.0e+3+N_s__Battery.*R_s__Battery.*u2.^2.*9.0e+3+N_p__Battery.*Rm__Motor.*u1.^2.*1.8e+2+N_p__Battery.*Rm__Motor.*u2.^2.*1.8e+2+N_s__Battery.*R_s__Battery.*Rm__Motor.*u1.^2.*6.0e+4+N_s__Battery.*R_s__Battery.*Rm__Motor.*u2.^2.*6.0e+4))];
out = reshape([mt1,mt2,mt3],3,1);
