function out = ModelJ_f_d(in1,in2,in3,in4)
%MODELJ_F_D
%    OUT = MODELJ_F_D(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    09-Nov-2021 15:27:11

%None
out = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,8]);
