# -*- coding: utf-8 -*-
"""
Created on Fri Mar 11 14:21:11 2022

@author: renkert2
"""

# -*- coding: utf-8 -*-
"""
Created on Tue Mar  8 18:02:49 2022

@author: renkert2
"""
import os
import sys
import openmdao.api as om

import Param
file_dir = os.path.dirname(__file__)
model_dir = os.path.join(file_dir, "../PlanarPTModelDAE")


os.chdir(file_dir)

#%% Import Test 1
# Parameters are imported through ParamSet's load() method.  Pass it 
# a .json file or path containing parameter metadata generated by MATLAB's 
# Param object.  
# ps = Param.ParamSet()
# f = open(os.path.join(model_dir, "ParamMetadata.json"))
# ps.load(f)

# # Temporarily make Propeller params Independent:
# for p in ps:
#     if p.parent == "Propeller":
#         p.dep = False

# # The parameter set can then be set up as before. 
# pg = Param.ParamGroup(ps)
# prob = om.Problem(model=pg)

# prob.setup()
# prob.run_model()
# om.n2(prob, outfile="n2_ParamImport.html")
# print(ps)

#%% Class Test
sys_dir = os.path.join(file_dir, "..")
if sys_dir not in sys.path:
    sys.path.append(sys_dir)
import PlanarPTModels as ppt

pg = ppt.PlanarPTParams()
prob = om.Problem(model=pg)

prob.setup()
prob.run_model()
om.n2(prob, outfile="n2_ParamImport.html")
print(pg._params)

